// Editorial cream design system.
// Fraunces (display serif) for headlines + italic accents, Inter for body,
// JetBrains Mono for labels. Pastel category tint per vertical.
//
// All 7 products preserved with their original data (name, domain, logo,
// tags, features). Display-only fields (initials, metric, metricSecondary)
// added for the cream Portfolio card treatment.

export const theme = {
  bg: '#F5EFE7',
  bgAlt: '#EFE7DA',
  ink: '#1E1A3D',
  inkMuted: '#4B4762',
  inkDim: '#8F8AA0',
  line: 'rgba(30,26,61,0.12)',
  primary: '#5848F8', // Vellmont brand indigo (from Tailwind brand-500)
  primaryDeep: '#3B2AD6',
  navySection: '#25204E',
  peach: '#E8B99A',
};

// Per-vertical pastel tint on cream. bg = card fill, ink = dark text on it,
// inkMuted = softer label, deep = hex accent, chip = pill background.
export const colorCategories = {
  healthcare: {
    label: 'HEALTHCARE',
    bg: 'bg-[#E3D9F5]',
    ink: 'text-[#2E1E5C]',
    inkMuted: 'text-[#5A4C82]',
    deep: '#5848F8',
    chip: 'bg-[#5848F8]/10 text-[#3B2AD6]',
    dot: 'bg-[#5848F8]',
    // Legacy dark-theme keys kept so any lingering imports don't crash.
    text: 'text-[#2E1E5C]',
    pillBg: 'bg-[#5848F8]/10',
    pillText: 'text-[#3B2AD6]',
    accent: 'text-[#5848F8]',
  },
  travel: {
    label: 'TRAVEL',
    bg: 'bg-[#D7EBD9]',
    ink: 'text-[#1F3B26]',
    inkMuted: 'text-[#4A6A50]',
    deep: '#3B7A4E',
    chip: 'bg-[#3B7A4E]/10 text-[#286038]',
    dot: 'bg-[#3B7A4E]',
    text: 'text-[#1F3B26]',
    pillBg: 'bg-[#3B7A4E]/10',
    pillText: 'text-[#286038]',
    accent: 'text-[#3B7A4E]',
  },
  finance: {
    label: 'FINANCE',
    bg: 'bg-[#F3DEC5]',
    ink: 'text-[#4A2A0E]',
    inkMuted: 'text-[#7A5535]',
    deep: '#B25A18',
    chip: 'bg-[#B25A18]/10 text-[#8F4210]',
    dot: 'bg-[#B25A18]',
    text: 'text-[#4A2A0E]',
    pillBg: 'bg-[#B25A18]/10',
    pillText: 'text-[#8F4210]',
    accent: 'text-[#B25A18]',
  },
  social: {
    label: 'EVENTS',
    bg: 'bg-[#EFDBE3]',
    ink: 'text-[#4A1E33]',
    inkMuted: 'text-[#7B4460]',
    deep: '#A63B72',
    chip: 'bg-[#A63B72]/10 text-[#7E2A56]',
    dot: 'bg-[#A63B72]',
    text: 'text-[#4A1E33]',
    pillBg: 'bg-[#A63B72]/10',
    pillText: 'text-[#7E2A56]',
    accent: 'text-[#A63B72]',
  },
  security: {
    label: 'ACCESS',
    bg: 'bg-[#DCE4D6]',
    ink: 'text-[#243020]',
    inkMuted: 'text-[#525E4A]',
    deep: '#4E6A3F',
    chip: 'bg-[#4E6A3F]/10 text-[#3B5231]',
    dot: 'bg-[#4E6A3F]',
    text: 'text-[#243020]',
    pillBg: 'bg-[#4E6A3F]/10',
    pillText: 'text-[#3B5231]',
    accent: 'text-[#4E6A3F]',
  },
  education: {
    label: 'EDUCATION',
    bg: 'bg-[#DDE2F0]',
    ink: 'text-[#181E3C]',
    inkMuted: 'text-[#4B5074]',
    deep: '#3A46A0',
    chip: 'bg-[#3A46A0]/10 text-[#2C3680]',
    dot: 'bg-[#3A46A0]',
    text: 'text-[#181E3C]',
    pillBg: 'bg-[#3A46A0]/10',
    pillText: 'text-[#2C3680]',
    accent: 'text-[#3A46A0]',
  },
  astrology: {
    label: 'ASTROLOGY',
    bg: 'bg-[#EAD9F3]',
    ink: 'text-[#3B1C4A]',
    inkMuted: 'text-[#6B4478]',
    deep: '#7B3EA2',
    chip: 'bg-[#7B3EA2]/10 text-[#5E2E7D]',
    dot: 'bg-[#7B3EA2]',
    text: 'text-[#3B1C4A]',
    pillBg: 'bg-[#7B3EA2]/10',
    pillText: 'text-[#5E2E7D]',
    accent: 'text-[#7B3EA2]',
  },
};

// ─── Products ────────────────────────────────────────────────────────────────
// Every original field preserved (id, name, suffix, domain, logo, logoBleed,
// banner, category, status, oneLiner, longDescription, tags, features, size).
// Added: `initials` + `metric`/`metricSecondary` for the cream card render.

export const products = [
  {
    id: 'medquepms',
    name: 'MedQue',
    suffix: 'PMS',
    displayName: 'MedQuePMS',
    initials: 'MQ',
    domain: 'medquepms.vellmontservices.com',
    logo: 'https://medquepms.vellmontservices.com/favicon-32.png',
    banner: '/banners/medquepms.png',
    category: 'healthcare',
    status: 'Production Ready',
    metric: { value: '09:42', label: 'Next patient', hint: 'On time' },
    metricSecondary: { label: 'Queue health', value: 'On time' },
    screenshots: {
      desktops: [
        '/screenshots/medquepms/desktop-overview.png',
        '/screenshots/medquepms/desktop-patients.png',
        '/screenshots/medquepms/desktop-ai-assist.png',
      ],
      mobiles: [
        '/screenshots/medquepms/mobile-staff-signin.png',
        '/screenshots/medquepms/mobile-patient-app.png',
        '/screenshots/medquepms/mobile-queue-email.png',
      ],
    },
    oneLiner: 'AI Clinic Operating System — queue to billing on one screen.',
    longDescription:
      'Cloud-based clinic OS unifying live token queue, doctor consultation workspace, AI Clinical Pre-Read, pharmacy POS, cashless/TPA workflow, billing, and a native patient app. Patients book via WhatsApp, missed-call, IVR, or AI chat; the doctor walks in already knowing them.',
    tags: [
      'Live Queue',
      'WhatsApp Booking',
      'AI Pre-Read',
      'Pharmacy',
      'Cashless / TPA',
      'Patient App',
    ],
    features: [
      'Queue Management',
      'Appointment Booking',
      'WhatsApp Booking',
      'IVR Booking',
      'Patient Mobile App',
      'Nurse Mobile App',
      'Doctor Workspace',
      'Clinical Pre-Read',
      'AI Notes',
      'Billing',
      'Pharmacy Management',
      'Lab Integration',
      'Telemedicine',
      'Prescription Management',
      'Patient History Timeline',
      'Analytics Dashboard',
      'Role Based Access',
      'DLT SMS Integration',
      'Payment Gateway Integration',
    ],
    size: 'flagship',
  },
  {
    id: 'vellroute',
    name: 'Vellroute',
    displayName: 'Vellroute',
    initials: 'VR',
    domain: 'vellroute.com',
    logo: '/logos/vellroute.svg',
    logoBleed: true,
    banner: '/banners/vellroute.png',
    category: 'travel',
    status: 'Live',
    metric: { value: '18', label: 'Live departures', hint: 'This week' },
    metricSecondary: { label: 'Guests', value: '86 guests' },
    oneLiner:
      'Tour Operator Operating System — leads, vendors, bookings, payments.',
    longDescription:
      'End-to-end operator OS that replaces the six WhatsApp groups and spreadsheets a tour business runs on. Leads, packages, bookings, vendors, payments, and a customer portal — coordinated in one screen.',
    tags: [
      'Tour Booking',
      'CRM',
      'Vendor Management',
      'Payments',
      'Customer Portal',
      'WhatsApp',
    ],
    features: [
      'Tour Booking',
      'CRM',
      'Leads',
      'Vendor Management',
      'Payments',
      'Invoices',
      'WhatsApp Integration',
      'Calendar',
      'Reporting',
      'Customer Portal',
      'Agent Management',
      'Tour Packages',
      'Booking Workflow',
    ],
    size: 'medium',
  },
  {
    id: 'vedjyotix',
    name: 'Vedjyotix',
    displayName: 'Vedjyotix',
    initials: 'VJ',
    domain: 'vedjyotix.com',
    logo: 'https://vedjyotix.com/favicon.svg',
    banner: '/banners/vedjyotix.png',
    category: 'astrology',
    status: 'Live',
    metric: { value: '3.2k', label: 'Kundlis generated', hint: 'This month' },
    metricSecondary: { label: 'Astrologers', value: 'Verified' },
    oneLiner: 'AI Astrology Platform with a verified astrologer marketplace.',
    longDescription:
      'Kundli, numerology, gun milan, love calculator and AI-generated reports — plus a marketplace where verified astrologers take chat and video consultations. Multilingual.',
    tags: ['Kundli', 'Gun Milan', 'Marketplace', 'AI Reports', 'Multilingual'],
    features: [
      'Kundli',
      'Numerology',
      'Love Calculator',
      'Gun Milan',
      'Rahu Kaal',
      'Astrologer Marketplace',
      'Online Consultation',
      'AI Astrology Reports',
      'Multilingual Support',
    ],
    size: 'medium',
  },
  {
    id: 'tutora',
    name: 'Tutora',
    displayName: 'Tutora',
    initials: 'TU',
    domain: 'tutorra.vellmontservices.com',
    logo: 'https://tutorra.vellmontservices.com/favicon.svg',
    category: 'education',
    status: 'Beta',
    metric: { value: '31', label: 'Active lessons', hint: 'Weekly progress' },
    metricSecondary: { label: 'Weekly progress', value: '+12.6%' },
    oneLiner: 'Tutor Marketplace — teachers, students, video sessions, payments.',
    longDescription:
      'A global tutor marketplace. Teachers list profiles and availability, students book, video sessions run inside the app, and payments settle through global rails. Ratings and scheduling baked in.',
    tags: [
      'Teacher Profiles',
      'Booking',
      'Video Sessions',
      'Global Payments',
      'Ratings',
    ],
    features: [
      'Teacher Profiles',
      'Booking System',
      'Video Sessions',
      'Student Dashboard',
      'Teacher Dashboard',
      'Global Payments',
      'Ratings',
      'Scheduling',
    ],
    size: 'small',
  },
  {
    id: 'invitesync',
    name: 'InviteSync',
    displayName: 'InviteSync',
    initials: 'IS',
    domain: 'invitesync.com',
    logo: 'https://invitesync.com/favicon.svg',
    banner: '/banners/invitesync.png',
    category: 'social',
    status: 'Live',
    metric: { value: '142', label: 'Confirmed', hint: 'Response rate 78.4%' },
    metricSecondary: { label: 'Response rate', value: '78.4%' },
    oneLiner: 'Invitation Management — every invite tracked, never missed.',
    longDescription:
      'Track every invitation — wedding, birthday, corporate — across web and mobile. Smart reminders, RSVP tracking, calendar sync, push notifications, and family sharing.',
    tags: [
      'Tracking',
      'Smart Reminders',
      'RSVP',
      'Calendar Sync',
      'Family Sharing',
    ],
    features: [
      'Invitation Tracking',
      'Smart Reminders',
      'Event Management',
      'RSVP Tracking',
      'Family Sharing',
      'Calendar Sync',
      'Push Notifications',
      'Event Templates',
      'Digital Invitations',
    ],
    size: 'small',
  },
  {
    id: 'vellbill',
    name: 'Vellbill',
    displayName: 'Vellbill',
    initials: 'VB',
    domain: 'vellbill.com',
    logo: 'https://vellbill.com/vellbill-mark.png',
    banner: '/banners/vellbill.png',
    category: 'finance',
    status: 'Live',
    metric: { value: '$42.8k', label: 'Collected', hint: 'Outstanding' },
    metricSecondary: { label: 'Outstanding', value: '$8,240' },
    oneLiner: 'Smart Invoicing — GST, quotations, expenses, recurring billing.',
    longDescription:
      'GST-compliant invoicing and expense management for Indian SMBs and freelancers. Quotations, recurring billing, customer management, payment tracking, and tax-ready reports.',
    tags: [
      'GST Invoices',
      'Quotations',
      'Recurring Billing',
      'Expense Tracking',
      'Tax Reports',
    ],
    features: [
      'GST Invoices',
      'Quotations',
      'Expense Tracking',
      'Customer Management',
      'Payment Tracking',
      'Recurring Billing',
      'Reports',
      'Tax Reports',
      'Dashboard',
    ],
    size: 'small',
  },
  {
    id: 'vellpass',
    name: 'Vellpass',
    displayName: 'Vellpass',
    initials: 'VP',
    domain: 'vellpass.vellmontservices.com',
    logo: 'https://vellpass.vellmontservices.com/logo-icon.png',
    category: 'security',
    status: 'Live',
    metric: { value: '24', label: 'Arrivals today', hint: 'Average check-in' },
    metricSecondary: { label: 'Average check-in', value: '00:38' },
    oneLiner:
      'Visitor & Gatepass Management — secure entry workflows for facilities.',
    longDescription:
      'Visitor and gatepass management system for apartments, offices, campuses and controlled facilities. Pre-approve visits, capture visitor details, issue digital gatepasses, notify hosts, track check-in/out, and keep a searchable audit trail for security teams.',
    tags: [
      'Visitor Logs',
      'Gatepass',
      'Host Approval',
      'Check-in / Out',
      'Security Desk',
      'Audit Trail',
    ],
    features: [
      'Visitor Registration',
      'Digital Gatepass',
      'Host Approval',
      'QR Check-in',
      'Check-out Tracking',
      'Security Dashboard',
      'Pre-approved Visits',
      'Visitor History',
      'Delivery Entry',
      'Staff Entry',
      'Notifications',
      'Role Based Access',
      'Audit Trail',
      'Multi-site Support',
    ],
    size: 'small',
  },
];

export const flagshipProduct = products.find((p) => p.size === 'flagship');
export const mediumProducts = products.filter((p) => p.size === 'medium');
export const smallProducts = products.filter((p) => p.size === 'small');

// Editorial type scale.
export const typography = {
  displayHeadline:
    'font-display font-normal tracking-[-0.02em] leading-[0.98] text-[52px] sm:text-[68px] md:text-[88px] lg:text-[108px]',
  sectionHeading:
    'font-display font-normal tracking-[-0.02em] leading-[1.02] text-[38px] sm:text-[48px] md:text-[58px] lg:text-[68px]',
  eyebrow:
    'font-sans font-medium text-[11px] uppercase tracking-[0.22em] text-[#5848F8]',
  eyebrowMuted:
    'font-sans font-medium text-[11px] uppercase tracking-[0.22em] text-[#8F8AA0]',
  italicAccent: 'font-display italic font-normal text-[#5848F8]',
  bodyLg: 'text-[17px] md:text-[18px] leading-[1.55] text-[#4B4762]',
  body: 'text-[15px] leading-[1.6] text-[#4B4762]',
  monoLabel:
    'font-mono text-[11px] uppercase tracking-[0.18em] text-[#8F8AA0]',
};
